= Buckeye Bars

Need snaks for office. Buckeyes are hard, lets try these in a pan instead.

One recipe I saw browns the butter. >this recipe also pours the peanut butter in the pan rather than pressing... interesting.
One recipe adds in creamcheese.

Should make 1 cookie sheet.
My cookie sheet has 14 cups of volumne.
The below has 13 1/4 cups of ingredients... hope it woks out.

== Ingredients

 * 3/4 cup butter, softened
 * 4 1/2 cups peanut butter, creamy
 * 6 cups powdered sugar
 * 2 1/4 tsp vanilla extract

== chocolate topping.

* 2 12- ounce packages of chocolate chips 3 cups, semi-sweet
* 1 1/2 tbsp butter

== Directions

 1. Alternate: instead of mixing in a stand mixer melt the butter (optional to brown it) and stir ingredients hot.
 1. Alternate: instead of pressing in the pan, pour into a greased pan.
 1. Peanut Butter LayerPlace butter, peanut butter, powdered sugar, and vanilla extract in a large bowl.
 1. Using an electric mixer, beat until smooth. The dough will be very thick and crumbly.
 1. Line a cookie sheet with parchment paper. Transfer the peanut butter dough into the pan and press firmly covering the bottom of the dish.
 1. melt the chocolate and butter in a double boiler.
 1. Pour the melted chocolate over the top of the bars and spread evenly using a spatula. Refrigerate for 1 hour. Carefully remove the bars from the pan by pulling up on the excess parchment paper, and transfer to a cutting board. Slice into squares with a sharp knife.
 1. Return to the refrigerator for at least 1 more hour, or until ready to serve.

Reference:
https://kitchenfunwithmy3sons.com/buckeye-bars/ = chill to serve ... I don't liek the sound of that.
