= Carrot Cake

Makes one 12 inch round pan or a 9x13 inch pan

== Ingredients:
 * 2 cups all purpose flour
 * 2 teaspoons baking powder
 * 1 1/2 teaspoons baking soda
 * 1 teaspoon salt
 * 1 teaspoon cinnamon
 * 2 cups sugar
 * 3/4 cup coconut oil
 * 4 eggs
 * 2 cups raw carrot, fine grated
 * 8 oz canned pineapple, crushed
 * 1/2 cup nuts (pecans or walnuts), chopped
 * 1 cup fresh or frozen coconut, shredded
 * 1/2 cup rum soaked raisens

== Directions:
 1. Sift together the flour, backing powder, baking soda, salt and cinnamon.
 1. Beat eggs to emulsion, then beat sugar into eggs, then beat in oil.
 1. Mix together the wet and dry.
 1. Fold in carrot, pineapple, nuts, and coconut.
 1. Bake at 350 deg F until a toothpick comes out clean. Bake time is unknown... One of these days I'll remember to time it.
 
== Notes:
 * The rum raisens need to be soaked for at least 24hours.
 * Best rum is Jamacan rum, which tasts like molasses.
 * You can sub the fresh coconut with dry, but if you do take advantage of this option by dry roasting it to add more complexity to the flavor.
 * It is traditional to top this with creamcheese frosting, but I find that has a disgusting amount of sugar and am looking for an alternative.

Reference:
This recipe came from Ilene Brege and has been the carrot cake recipe used by Wendy's family for years and years (with some modification).
