= Chicken Balti Pies

Last year for PI day I made the "4 Chicken and Chorizo Individual Pies" recipe by the same author.
This year I want to try this new recipe but keep the amounts similar to that of last year.
So this is the crust from 4 chicken with the filling of Chicken Balti

Makes 2 9" pie pans

== Ingredients
=== The hot water crust pastry:
 * 500g / 18oz Plain or all-purpose flour
 * 215g / mls Water
 * 115g / 4oz Butter
 * 125 / 4½ oz Lard or solid vegetable fat
 * 8g / 1tsp Salt
 * 2 tsp Garam Masala
 * 1 Large Egg (Egg-wash)

=== The Curry Filling:
 * 498g / 14oz Chicken thighs, deboned
 * 170g or 1 Medium size onion
 * 25g Fresh Cilantro leaves
 * 300g Frozen tomatoes (chopped small)
 * 1 Tbs minced ginger
 * 4 Garlic cloves
 * 3 serrano (chopped small)
 * 2 tsp kashmiri chilli powder
 * 1 tsp Turmeric powder
 * 2 tsp Garam Masala
 * 5g / 1 tsp Salt
 * 60mls / 4tbls oilve oil
 * 150mls Chicken stock or water
 * 2 tsp sour cream

== Notes
 * the pie filling was 849 grams in total after chilled in the fridge. For 2 9" pies this needs to be more... maybe a target of 1000 grams would fit better next time.
 * there is soo much wasted dough in large pies... maybe I should try to make a square hand pie next time.
 * The flavor was too heavy in the garam masala area. It may be worth looking up an actual curry recipe with garam masala and see what ratios of flavors are in there and adjust this one.

== Directions
=== Prep the pie dough
 1. Mix the salt and Garam masala into the flour, and form a well.
 1. Place the water on a low heat and add the butter and lard to the pan, bring to a simmer.
 1. Soon as the fats have melted, pour the hot liquid into the flour well in the bowl, and bring it all together.
 1. Tip the contents of the bowl out onto the work surface.
 1. Gently knead the dough until it all comes together.
 1. Cut the pastry onto 2 pieces, 2 thirds, for the base of the pie, and 1 third for the top of the pie.
 1. Cover in plastic wrap or food bags, and place in the fridge for at least 1 hour before using.

=== Making the filling:
 1. In a medium size frying pan, or curry pan if you have one, add the 4 tablespoons of oil and get it hot.
 1. Start by frying off your onions until they’re translucent, and just starting to colour.
 1. Add you chopped ginger and garlic, stir fry for 1 minute.
 1. Add the tomatoes to the pan, and mix them in.
 1. Next: add the chicken, stir for 1 minute.
 1. Now add your mixed spices and salt, combine it all together.
 1. Add the chopped serrano chillies and mix those in.
 1. Pour in your chicken stock or water and bring to a low simmer for 5 minutes.
 1. Add the 2tsp of sour cream, and mix in.
 1. Finally add the chopped fresh Coriander leaves and mix those in.
 1. Turn off the heat, cover the pan and allow to cool completely.

=== Putting the pies together (day after filling is made):
 1. Make up your egg wash, using 1 small egg and a dash of milk, whisk until smooth and runny.
 1. Grease pie plates.
 1. Roll out your pastry and cut bottoms and lids to fit the pie plates.
 1. Place the pastry bases in the pie tins, press the pastry right down into the corners, make sure to leave some pastry sticking over the rim of the pie tin.
 1. Fill the cases with the now cooled Balti filling to just below the top of the pastry.
 1. Tap the tins on your bench to release any trapped air bubbles.
 1. At this point, preheat your oven to, 170°C / 340°F / Gas mark 3.
 1. Brush egg wash all around the edge of the pastry.
 1. Crimp the edges by: Place the lids on the top of the pie bases, and gently press it down, using your thumbs and forefingers, neatly crimp the 2 pastries together.
 1. Cut 2 vent slits in the top of each pie.
 1. Give each pie a good coat of the egg wash.
 1. Place the pies in middle of the preheated oven, and use the bottom element, if you have one.
 1. Now set your timer for 40 minutes (or longer for glass pie plates 60 - 90 min?).

== Reference
https://profoodhomemade.com/chicken-balti-pies/
