= Chocolate Mousse
This came from Good Eats. Good enough that it didn't need Alteration.

== Ingredients

 * 12 oz chocolate, semisweet
 * 1 3/4 cup whipping cream
 * 3 ounces of expresso (or strong coffee)
 * 1 Tbs dark rum
 * 4 Tbs butter
 * 1 Tbs gelatin (flavorless)

== Directions
 1. Chill 1 1/2 cups whipping cream in refrigerator. Chill metal mixing bowl and mixer beaters in freezer.
 1. In top of a double boiler, combine chocolate chips, coffee, rum and butter. Melt over barely simmering water, stirring constantly. Remove from heat while a couple of chunks are still visible. Cool, stirring occasionally to just above body temperature.
 1. Pour remaining 1/4 cup whipping cream into a metal measuring cup and sprinkle in the gelatin. Allow gelatin to "bloom" for 10 minutes. Then carefully heat by swirling the measuring cup over a low gas flame or candle. Do not boil or gelatin will be damaged. Stir mixture into the cooled chocolate and set aside.
 1. In the chilled mixing bowl, beat cream to medium peaks. Stir 1/4 of the whipped cream into the chocolate mixture to lighten it. Fold in the remaining whipped cream in two doses. There may be streaks of whipped cream in the chocolate and that is fine. Do not over work the mousse.
 1. Spoon into bowls or martini glasses and chill for at least 1 hour. Garnish with fruit and serve.
 1. (If mousses are to be refrigerated overnight, chill for 1 hour and then cover each with plastic wrap)

== Reference
https://www.foodnetwork.com/recipes/alton-brown/chocolate-mousse-recipe0-1955790
