= Chocolate Avocado Pudding, Raw, Vegan, Not Gross 
 by Tastemade
 
I've made this a lot over the years. The video and recipe used to be hosted by Tastemade but at some point was taken down.
 
== Ingredients
 * 2 ripe avocados
 * 3 Tbs Coconut oil
 * 1/4 tsp salt
 * 1/2 Cup Maple syrup
 * 1/2 tsp Nama Shoyu (soy sauce)
 * 1/2 tsp Balsamic Vinegar
 * 1/2 Cup Dutch Processed Cocoa Powder
 
== Directions
 1. Coconut oil goes in a pan to melt.
 1. Avocado, salt, maple syrup, Nama Shoyu, and balsamic vinegar go into a food processor. Pulse until mixed.
 1. Turn on the food processor and drizzle in the oil like you are making mayo.
 1. With the food processor off, add in the cocoa powder. Mix gently with a spoon to get the powder wet, then the food processor goes on for a minute.
 1. Scrape the sides of the food processor and blend for another minute.
 1. Eat straight away, chill in the fridge, or dollop onto a silpat and put in the freezer for a cold treat.
  
 A fan re-uploaded the original video
 https://www.youtube.com/watch?v=ghF2-mLIUc8
