= Chocolate Beet Cake
This will have a beet flavor and in honesty needs something to help meld the bitter of the chocolate to the beet flavor. It has an awesome moistness though.

== Ingredients
=== Cake:
 * 2 cups sugar
 * 2 cups flour
 * ½  tsp salt
 * 2 tsp baking powder
 * 1 tsp baking soda
 * 1/8 tsp cayenne pepper powder
 * 3-5 oz chocolate (unsweetened or semi-sweet)
 * 4 eggs, beaten
 * ¼ cup butter
 * 3 cups beets, finely grated (let juice drain and don't pack the cups unless you want a beety flavor)

=== Frosting:
 * 2 cup whipping cream
 * 12 oz chocolate (milk, semi-sweet, or bitter-sweet)

== Directions
=== Cake:
 1. Add sugar, flour, salt, baking powder, and baking soda to a large mixing bowl.
 1. Mix the dry ingredients until well blended.
 1. Melt the chocolate and butter in a double boiler.
 1. Beat the eggs and butter together and then the egg/oil and chocolate together until well blended.
 1. Mix in the beets with the chocolate/egg/oil
 1. Add the wet to the dry and mix.
 1. Pour into a greased 9x13 pan.
 1. Bake in a preheated oven at 375 deg F for 30 -40 min or until fork comes out clean.

=== Frosting:
 1. Bring whipping cream to a boil then remove from heat.
 1. Add chocolate and cover (do not stir).
 1. Wait 5 min
 1. Stir until smooth and transfer to a bowl and cool in the fridge overnight.
 1. The next day remove the frosting well in advance to let it warm up to room temp.
 1. Mix until smooth and spreadable and apply to cake.
 
== Notes
 * Theses need to be made a day in advance to let the cake cool before adding the frosting.
 * This cake will rise in the middle

== Reference
The beet cake came from “Asparagus to Zucchini” and the frosting came from “Better Homes and Gardens: New Cook Book” page 186 (ISBN:0696225654)
