= Coconut Birthday Pie

This is my first time to make a coconut cream pie. I showed Wendy one with chrushed pineapple and she thought that sounded good.
That one was a no cook recipe and we don't really like stuff that goes into instant pudding so remaking something from a different recipe.

== Ingredients
=== For the crust:
figure something out... you will need to have it fully baked. I'm going to use vanilla wafers, coconut, and make a butter crumb.

=== For the filling:
 * 4 large egg yolks
 * 1/4 cup (30g) cornstarch
 * 1 (14 ounce) can full fat coconut milk
 * 1 cup half-and-half
 * 2/3 cup (130g) granulated sugar
 * 1/4 tsp salt
 * 1 cup (80g) sweetened shredded coconut, gonna swap this for fresh frozen coconut by volume.
 * 2 Tbs (30g) butter, softened to room temperature
 * 1 tsp pure vanilla extract
 
=== Whipped Cream
 * 1 - 1/2 cups (360ml) cold heavy cream
 * 3 Tbs (20g) sugar
 * 3/4 tsp pure vanilla extract
 * optional for garnish: unsweetened coconut shavings, coconut chips, or sweetened shredded coconut*



== Directions over 3 days

=== Day 1

 1. toast some coconut enough for this and garnish.
 1. Throw it in the half and half and seperately the whipping cream, refridgerate for later.
 1. Make piecrust and refridgerate (if pie filling is hot will this work?)
 
=== Make the coconut filling:

 1. Whisk the egg yolks and cornstarch together. Set aside.
 1. Whisk the coconut milk, half-and-half, granulated sugar, and salt together in a medium saucepan over medium heat.
 1. Whisking occasionally, bring to a boil. Boil for 2 minutes, then reduce temperature to medium-low heat.
 1. Once boiling, remove about 1/2 cup of the mixture and, in a slow and steady stream, whisk into the egg yolk and cornstarch mixture.
 1. Keep those egg yolks moving so they don’t scramble. In a slow and steady stream, pour and whisk the egg yolk mixture into the pot.
 1. The pudding will immediately begin to bubble and thicken. Stand back and use caution as the bubbles may burst. Whisk and cook for 1 minute and 30 seconds.
 1. Remove from heat and stir in the coconut, butter, and vanilla.
 1. Pour warm filling into cooled pie crust. Cover tightly with plastic wrap directly on the surface of the pudding (to prevent a skin from forming) and refrigerate for at least 3 hours or overnight until chilled and thickened. Pie may be refrigerated for up to 1 day.
 
=== For the whipped cream

 1. Strain the heavy cream.
 1. Whip the heavy cream, sugar, and vanilla extract on medium-high speed until medium peaks form, about 3-4 minutes.
 1. Pipe or spread the whipped cream on top. Garnish with extra coconut, if desired. Chill the pie uncovered up to a few hours or you can serve it immediately.


Notes:
the pineapple goes in the filling ... probably after the thickening?

Reference:  

https://sallysbakingaddiction.com/coconut-cream-pie/
