= Corn Pudding
Tyrinslys Valinlore
  
This recipe is from http://foodwishes.blogspot.com/2016/11/creamy-corn-pudding-perfect-for.html[here].
I plan to make it tomorrow. We will see how it turns out.

== Ingredients

* 2 pounds frozen yellow corn (buy premium quality)
* 3 tablespoons maple syrup
* 6 large eggs
* 1/2 cup milk
* 3 teaspoons kosher salt (1 1/2 teaspoon fine salt)
* 1/4 teaspoon cayenne
* 1/4 cup all-purpose flour
* 1 teaspoon baking powder
* 1/2 cup melted butter, divided (2/3 for batter, 1/3 for baking dish)
* 1 1/2 cups heavy cream

== Instructions

. Thaw and drain frozen corn
. Blend: [Tip: add half of the corn, then the other ingredients, then the rest of the corn. This will keep the powdered things from exploading when the blender is turned on.]
  * corn (from 5% to all depending on how much whole corn you want in your pudding). [here left 1 cup whole]
  * maple syrup
  * eggs
  * milk
  * salt
  * cayenne
  * flour
  * baking powder
. Pour into a bowl, add in melted butter and cream. Mix with a wisk.
. Prep the baking dish with the butter (8" x 11" pan)
. Place baking dish on a sheet pan lined with a silpat and bake at 350 F. for between 60 and 75 minutes, or until brown and just set.
