= DoubleChocolateEspressoCookies

A&M: Two warnings about these cookies: don’t give them to young children before bedtime and don’t leave them lying around,
if you want any left for yourself. These cookies are crisp on the edges and have a chewy middle strewn with pockets of
soft chocolate. The espresso powder, as KelseyTheNaptimeChef noted, amplifies the chocolate, but not the sweetness,
making it a grown-up cookie. When making any cookies, make sure to cream the butter really well— this aerates the cookies
and integrates the sugar—but be conservative with your mixing once the dry ingredients are added.

== Ingredients:

 * 18 tablespoons (2 1/4 sticks) unsalted butter, at room temperature
 * 1 cup sugar
 * 1 cup light brown sugar
 * 2 large eggs, at room temperature
 * 2 1/2 cups all-purpose flour
 * 3/4 cup unsweetened cocoa powder
 * 1 teaspoon baking soda
 * 1 teaspoon kosher salt
 * 2 tablespoons instant espresso powder, like Medaglia D’Oro, or similar
 * 12 ounces semiweet chocolate chips

== Directions:
1. Heat the oven to 350°F.
2. In a large bowl, cream the butter and sugars until light and fluffy. Add the eggs one at time, mixing after each addition to make sure they are well combined.
3. In a separate bowl, combine the dry ingredients: flour, cocoa powder, baking soda, salt, and espresso powder. I use a whisk to make sure they are well blended.
4. With the mixer on low, slowly add the dry ingredients to the wet ingredients, scraping down the sides of the bowl as needed. Mix everything until the ingredients are fully
combined, but do not overbeat. Using a wooden spoon, stir in the chocolate chips.
5. Line a baking sheet with a Silpat mat or parchment paper. Using a 1 1/2-inch ice cream scoop or a rounded teaspoon, drop the dough on the sheet 2 inches apart. Bake for 10 to 12 minutes, or until the tops look dry. Do not overbake, or the cookies will not be chewy. Cool on a wire rack and serve.

Reference:  
This recipe came from __The Food52 Cookbook__ but may have changed since adding it to my collection.
