== Red Sauce

== Ingredients

* 1 onion, finely diced
* 1 rib celery, finely diced
* 1 pinch salt
* 4 cloves garlic, minced
* 2 (28 ounce) cans whole peeled San Marzano tomatoes
* 2 teaspoons white sugar
* 1 teaspoon salt
* 1 teaspoon anchovy paste
* 1 teaspoon white wine vinegar
* 1/4 tablespoons dried basil
* 1/8 tablespoons dried oregano
* 1/16 tablespoons dried rosemary
* 1/8 tablespoons dried parsley
* 1 pinch red pepper flakes
* 1 tablespoon tomato paste
* 2 tablespoons chopped Italian flat-leaf parsley


== Directions

1. Place olive oil, onion, celery, and a pinch of salt into a large heavy saucepan or Dutch oven over medium-low heat. Cook until onions are very soft, about 15 minutes, stirring occasionally.
1. Mix garlic into onion mixture and cook just until fragrant, about 1 more minute.
1. Pour tomatoes and their juice into a large mixing bowl and use your hands to crush the tomatoes until they look pureed.
1. Mix sugar, 1 teaspoon salt, anchovy paste, white wine vinegar, Italian herbs, and red pepper flakes into vegetable mixture. Raise heat to medium and cook just until liquid has evaporated.
1. Stir in tomato paste and bring to a simmer.
1. Pour in San Marzano tomatoes and parsley. Bring sauce to a simmer, turn heat to low, and simmer for 1 1/2 hours, adding a little water as the sauce cooks down. Stir occasionally.

== Reference
https://www.allrecipes.com/recipe/220854/chef-johns-italian-meatballs/
