= Meatballs

so far this is verbatium... but I don't like a few things about it. Experimentation will commence.

== Ingredient

 * 2 Tbsp. extra-virgin olive oil, plus more for baking sheet
 * 2 large eggs
 * 1½ cups panko (Japanese breadcrumbs)
 * ½ cup milk or water
 * 1¼ tsp. Diamond Crystal or ¾ tsp. Morton kosher salt
 * 1 tsp. garlic powder
 * Freshly ground black pepper
 * 1 oz. Parmesan, finely grated (about ½ cup), plus more for serving
 * 1 lb. ground beef (20% fat) or other ground meat
 * Warm homemade or store-bought tomato sauce and torn basil leaves (for serving)

== Instructions

1. Place rack in top third of oven; preheat to 425°.
1. Lightly brush a large rimmed baking sheet with oil.
1. Using a sturdy wooden spoon, vigorously stir eggs, panko, milk, salt, garlic powder, several cranks of pepper, 1 oz.
1. Parmesan, and remaining 2 Tbsp. oil in a medium bowl until nearly a smooth paste.
1. Mix in one quarter of meat (combining just a small amount of meat in the beginning makes it easier to incorporate the rest without overmixing).
1. Add remaining meat and mix well to thoroughly combine, but don’t overwork it.
1. Using oiled hands, form into 8 large meatballs and place on prepared baking sheet.
1. Bake meatballs until well browned underneath, about 15 minutes.
1. Using a stiff metal spatula, pry up and turn over meatballs (they may want to stick a bit).
1. Bake until browned on second side and an instant-read thermometer inserted into the center of each one registers 160°, 5–7 minutes.
1. Divide meatballs among plates and spoon some sauce over.
1. Top with basil and more Parmesan.

== Reference:
https://www.bonappetit.com/recipe/weeknight-meatballs
