= Pumpkin Pie
Pumpkin pie for me has to be spicy and have a lot of pumpkin in it.

##Ingredients:
 * 1 cup sugar
 * 1 tsp cinnamon
 * 1/2 tsp ginger
 * 1/4 tsp nutmeg
 * 1/2 tsp salt
 * 2 tbs flour
 * 2 cups pumpkin
 * 1 cup milk
 * 2 eggs, beaten
 * 1 tablespoon butter
 
##Directions:
  1. Combine sugar, spices, and flour.
  1. Add all other ingredients and beat until smooth.
  1. Pour into unbaked pie shell.
  1. Bake at 400 degF for 15 minutes.
  1. Reduce oven temperature to 350 degF and bake another 45 min or until knife goes in and comes out of the center cleanish.

##Notes:
 * With scrapes of dough you can decorate the top at the last 20 min of cooking.
 * I have used this recipe with sweet potato or summer squash instead of pumpkin and it works just fine.
 * Using sweet squash instead of pumpkin I used only 1/2 cup of sugar and it still tasted very sweet.

##Laboratory Notes:
 * I used the ginger snap cookie crust from my cheesecake recipe and it turned out good. The crust had more spice than the pie though.
 * I tried a gramcracker crust and it turned out chewy. I thought it was from stale crackers so on my second attempt I used the oven to cook the crackers for 15 min. This new crust was not only chewy but seemed to pull moisture out of the pie filling as it baked.
 * Next experiment can be to add a egg wash in hope to keep the gram from the pie filling to have the crust stay crispy.

##References
The base for this recipe was from Food.com as recipe number 2393 but has been changed so much maybe I don't need this here any more.
