= SHAKSHUKA

Taken from the internet and modified to my liking. This dish is great because it makes enough sause to do the egg thing twice and after than it is a good dipping sause for grilled cheese.

== Ingredients
* 10.4 oz of red peppers (roughly 2 bell)
* 6.5 oz onions (3 small onions)


* 4 garlic cloves, finely chopped
* 2 tsp paprika
* 1 tsp cumin
* 1/4 tsp chili powder
* 1/4 tsp cayenne pepper
* 1 Tbs harissa

* 1 14.5 oz can whole peeled tomatoes, diced
* 14 oz of frozen tomatoes, peeled and diced (if you need to sub this go with a single 28 oz can for all tomatoes)
* 6 large eggs
* salt and pepper, to taste
* 1 small bunch fresh cilantro, chopped
* 1 small bunch fresh parsley, chopped (optional)

== Directions
1. Heat olive oil in a large sauté pan on medium high heat. Add the chopped bell pepper and onion and cook for 5 minutes or until the onion becomes translucent.
1. Add garlic and spices and cook an additional minute. The harissa will need some teasing to become more liquid. Add a bit of water to deglaze the pan and protect the garlic form burning.
1 Pour the can of tomatoes and juice into the pan. Season with salt and pepper and simmer for 10 minutes.
1. Use your large spoon to make small wells in the sauce and crack the eggs into a ramkin before tranfering to each well. Cover the pan and cook for 5 minutes, or until the eggs are done to your liking.
1. Tranfer to a broialer for 3-4 minutes until the egg white is cooked.
1. Garnish with chopped cilantro/parsley.
1. Serve, eggs will need to be seasoned.

== Reference
https://downshiftology.com/recipes/shakshuka/
