= Stabilized Whipped Cream

Makes about a scant 2 cups

== Ingredients:
 * 1 teaspoons powdered gelatin (unflavored)
 * 4 teaspoons water
 * 1 cup whipping cream
 * 1 tablespoon granulated sugar
 * Flavor extract (optional) 6-ish drops

== Directions:
 1. Refrigerate mixing bowl and beaters in the fridge for a minimum of 15 minutes. Ensure cream is very cold as well. This will all help cream whip better.
 1. Place water in heatproof cup and sprinkle gelatin on top to bloom. Wait 5 minutes.
 1. Place cup in a small sauce pan filled with simmering water. Once gelatin becomes liquid, take it out of the water. Let cool on the counter.
 1. Immediately start beating the cream and sugar in a stand mixer fitted with the chilled bowl. Whip on medium speed and then increase to medium-high.
 1. Check on the gelatin. It should no longer be hot but still runny.
 1. Once the beaters leave tracks in the cream, pour the gelatin into the bowl slowly and steadily. Aim for the area in between the whisk and the bowl. If desired, add extract and food color before the cream becomes stiff.
 1. Stop beating once the cream turns stiff. Do not over whip.
 1. Use cream to assemble cooled dessert immediately. 
 
== Notes:
 * The sugar can be reduced.

Reference:
https://www.indulgewithmimi.com/stabilized-whipped-cream-with-gelatin-for-piping/
