= Made up lemon sponge cake

I want to make a lemon sponge cake. Most of the recipies I see have butter in them. Traditionally butter was not added to sponge cake.
I want to try adapting the plain sponge recipe by adding like 1 lemon of zest and replacing 1/4 cup of the water with lemon juice.

Makes ???

== Ingredients
 * 6 large eggs, separated
 * 1/4 cup fresh lemon juice
 * 1/4 cup warm water
 * 1-1/2 cups all-purpose flour
 * 1/2 teaspoon salt
 * 1 teaspoon vanilla extract
 * 1/2 teaspoon cream of tartar
 * 1-1/2 cups sugar, divided some for white some for yolk.

== Directions
 1. Preheat oven to 325°.
 1. Let eggs stand at room temperature for 30 minutes.
 1. Sift flour and salt.
 1. In a large bowl, beat yolks until slightly thickened. Gradually add 1 cup sugar, beating until thick and lemon-colored. Blend in water and vanilla. Add dry ingredients to yolk mixture; mix well.
 1. In another bowl, beat egg whites and cream of tartar on medium speed until soft peaks form. Gradually beat in remaining sugar, about 1 tablespoon at a time, on high until stiff glossy peaks form and sugar is dissolved. Fold a fourth of egg whites into the batter, then fold in remaining whites.
 1. Gently spoon into an ungreased 10-in. tube pan. Cut through batter with a knife to remove air pockets. Bake on the lowest oven rack until cake springs back when lightly touched, 55-60 minutes. Immediately invert the pan; cool completely.
 1. Run a knife around side and center tube of pan. Remove cake to a serving plate. If desired, serve with ice cream topping.

== Notes
 * nothing here just yet

== Reference
https://www.tasteofhome.com/recipes/traditional-sponge-cake/
