= Apple Pie Bars

This looks good, lets try them.

== Ingredients
=== For the crust:
 * 1 pound (4 sticks) unsalted butter, at room temperature
 * 3/4 cup granulated sugar
 * 1/2 cup light brown sugar, lightly packed
 * 2 teaspoons pure vanilla extract
 * 4 cups all-purpose flour
 * 1 1/2 teaspoons kosher salt
 * 1/2 cup chopped walnuts
 * 1 teaspoon ground cinnamon

=== For the apple filling:
 * 1 1/2 pounds Granny Smith apples, peeled, quartered, cored, and sliced 1/8 inch thick (3 large)
 * 1 1/2 pounds Golden Delicious apples, peeled, quartered, cored, and sliced 1/8 inch thick (3 large)
 * 2 tablespoons freshly squeezed lemon juice
 * 1/4 cup granulated sugar
 * 1 teaspoon ground cinnamon
 * 1/8 teaspoon ground nutmeg
 * 4 tablespoons (1/2 stick) unsalted butter

== Directions
 1. Preheat the oven to 375 degrees.
 1.    For the crust, place the butter, granulated sugar, brown sugar, and vanilla in the bowl of an electric mixer fitted with the paddle attachment and beat on medium speed for 2 minutes, until light and creamy. Sift the flour and salt together and, with the mixer on low, slowly add to the butter-sugar mixture, beating until combined. Scatter two-thirds of the dough in clumps in a 9 x 13-inch baking pan and press it lightly with floured hands on the bottom and 1/2 inch up the sides. Refrigerate for 20 minutes. Bake for 18 to 20 minutes, until the crust is golden brown, and set aside to cool.
 1.    Meanwhile, put the mixing bowl with the remaining dough back on the mixer, add the walnuts and cinnamon, and mix on low speed to combine. Set aside.
 1.    Reduce the oven to 350 degrees.
 1.    For the filling, combine the Granny Smith and Golden Delicious apples and lemon juice in a very large bowl. Add the granulated sugar, cinnamon, and nutmeg and mix well. Melt the butter in a large (10-inch-diameter) pot, add the apples, and simmer over medium to medium-low heat, stirring often, for 12 to 15 minutes, until the apples are tender and the liquid has mostly evaporated. Spread the apples evenly over the crust, leaving a 1/2-inch border.
 1.    Pinch medium pieces of the remaining dough with your fingers and drop them evenly on top of the apples (they will not be covered). Bake for 25 to 30 minutes, until the topping is browned. Cool completely and cut into bars.

Notes:
line the baking pan with parchment paper before making the crust.
